apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: openhackapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: openhackapp-deployment
    spec:
      containers:
        - name: openhackapp
          image: 'selcukusta/openhack-core:3.0.0'
          ports:
            - containerPort: 5000
          resources:
            requests:
              memory: "512M"
              cpu: "0.25"
            limits:
              memory: "1Gi"
              cpu: "0.50"
---
apiVersion: v1
kind: Service
metadata:
  name: openhackapp-service
  labels:
    name: openhackapp-service
spec:
  ports:
    - port: 5000
      name: "default"
      targetPort: 5000
      protocol: TCP
  selector:
    app: openhackapp-deployment
  type: LoadBalancer